### ISSUE TITLE
Problemi sa kretanjem

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG017-anthill#2]
Nisam siguran da ovo mozete lako da popravite, ali probajte:

- Ponekad se detektuje kolizija, a da nije doslo do iste
- Ponekad se mravi blokiraju i ne mogu dalje da se krecu
- Ponekad kad se doda cetvrti mrav, ne krece se pravilno - ne ide za ostalim mravima, nego cas pored, cas se poklapa sa nekim od prethodnih

**Comment by Nikola-Smiljanic** [comment]
1)problem sa kolizijom resen (koristio sam abs umseto fabs kod oduzimanja double vrednosti).

**Comment by Nikola-Smiljanic** [comment]
2)problem sa dodavanjem novih mrava resen(ranije dodavanje mrava je gledalo smer prvog mrava
umseto poslednjeg).

**Comment by Nikola-Smiljanic** [comment]
3)ispravljena greska kod blokiranja mrava i njihovog zaglavljivanja.
